### ISSUE TITLE
Test Case 1: Verifying that urls.txt is non-empty

### ISSUE THREAD

**Issue by StayCool21** [StayCool21/CS325_Project4#2]
Sydney - I figured that because you created this test case beforehand, I'll let you take this one.

**Comment by sbar821** [comment]
To ensure that `url.txt` is nonempty, we need to check to see if there is at least one URL.

**Comment by sbar821** [comment]
Refreshed test return state when it finds nothing in `url.txt` and improved documentation in the function `get_url_from_file`.

**Comment by StayCool21** [comment]
Looks good to me! Feel free to close it out.
