### ISSUE TITLE
Test Case 3: Check whether sanitized or unsanitized files are correctly written to destination

### ISSUE THREAD

**Issue by StayCool21** [StayCool21/CS325_Project4#3]
Once again, unless you're feeling otherwise, I'd be happy to delegate this one to you, Sydney, as well, considering it's already implemented in the existing code.

**Comment by sbar821** [comment]
This test would need to ensure that the function `write_stories_to_file` will throw a proper exception if some error occurs- i.e. duplicate file names or access issues.

**Comment by sbar821** [comment]
Ensured existing try-catch block does exactly as mentioned before with added documentation.

**Comment by StayCool21** [comment]
Great job on this one too, looks good to me!
