### ISSUE TITLE
Test Case 2: Check whether URLs in url.txt are accessible URLs

### ISSUE THREAD

**Issue by StayCool21** [StayCool21/CS325_Project4#4]

**Comment by StayCool21** [comment]
Well, we know that we are going to be using CBS News web articles, but we also need to check that they also exist past the `www.cbsnews.com` domain.

**Comment by StayCool21** [comment]
Created another function in `mod1_funct1.py` for testing that all URLs return a error code of 200 called `test_urls`. Implemented this in lines 51-66. 
Right now, it is being called in the `main` of `run.py` on line 35 right after all URLs are checked that they are from the correct domain. I believe this is ready for review.

**Comment by sbar821** [comment]
Looks good!
