### ISSUE TITLE
Test Case 4: Verify Summary Writing

### ISSUE THREAD

**Issue by StayCool21** [StayCool21/CS325_Project4#5]

**Comment by StayCool21** [comment]
We need a check to ensure that the function `write_summary_to_file` in `mod3_funct1.py` correctly writes summaries to files.

**Comment by StayCool21** [comment]
Instead of creating another function, I think it would be best if we simply just checked if the summary that was written to the output file is non-empty. This might not be as full-scale as it should, but it should do the job.
Added lines 55-58 of `run.py` to check this. Should be good for review!

**Comment by sbar821** [comment]
Double checked- ready to close!
