### ISSUE TITLE
Test Case 5: Verify Raw Data Retrieval from get_raw_from_file

### ISSUE THREAD

**Issue by StayCool21** [StayCool21/CS325_Project4#6]

**Comment by sbar821** [comment]
Issues arise if the proper page no longer has text, resulting in a chain reaction across all functions. Implementing an error call forces a stop to prevent the chain reaction.

**Comment by sbar821** [comment]
I implemented a proper error call in an if-else in the function `get_raw_from_file` that either returns the story array or calls the error. Just needs checked!

**Comment by StayCool21** [comment]
Took a look over the implementation and it looks great! Close this one out.
