### ISSUE TITLE
Test Case 8: Verify Proper Handling of Duplicate URLs in urls.txt

### ISSUE THREAD

**Issue by StayCool21** [StayCool21/CS325_Project4#9]

**Comment by StayCool21** [comment]
We need a good way to ensure data integrity of the input URLs by making some scheme to check if an input URL has any duplicates, and if so, to not create any unsanitized/sanitized/summarized file multiple times.

**Comment by StayCool21** [comment]
Added a check for unique URLs in lines 22-30 of `mod1_funct1.py`, inside the `get_url_from_file` function to remove any duplicates from the input file and return the new URL array. I believe this is ready for review.

**Comment by sbar821** [comment]
Good work! This improvement will save time for the user. Ready to close.
